sonar.projectKey=apply-the_boundline-adapter-speckit
sonar.organization=apply-the

sonar.projectName=boundline-adapter-speckit
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.rs

sonar.sourceEncoding=UTF-8

sonar.rust.lcov.reportPath=lcov.info